### ISSUE TITLE
I am on the Alpha 10.10.10 version, why can't I load this?

### ISSUE THREAD

**Issue by BzQxingxingqiu** [Trawis/SoftwareIncDLLModifications#14]
I am on the Alpha 10.10.10 version, why can't I load this?

I put the mod directly into it. The mod is also turned on but there are no successful tips in the game. There is no window

**Comment by BzQxingxingqiu** [comment]
I'm an offline version.

**Comment by Trawis** [comment]
You need to subscribe to trainer via steam workshop as I'm only supporting that. Sorry!
