### ISSUE TITLE
Alpha 10.2.1 Max Code, Max Art not functioning

### ISSUE THREAD

**Issue by AdamC1228** [Trawis/SoftwareIncDLLModifications#4]
Game Version: 10.2.1
Expected Outcome: Code and Art percentages should be 100%.
Actual Outcome: Code and Art set to a very low percentage relative to amount of time spend developing product. 

Proposed fix: Development time and progress are multiplied together to produce the completion percentage. Set the ArtDevTime to be the complementary multiple to produce 100% completion.

DevTime * ArtProgress = PercentComplete

Example of solution:             
            ((SoftwareAlpha)WorkItem).ArtDevTime = 10f;
            ((SoftwareAlpha)WorkItem).ArtProgress = 10f;

Solution Is validated against the current master branch of this repository and game version 10.2.1

**Comment by Kr4ken-9** [comment]
Under 10.3.2, my test results are different.
Upon settings ArtDevTime and ArtProgress to 10, it will just set art units to 100 (same with code)
This usually causes quality issues because (I'm guessing) the recommended units is below 100, and having the units above that decreases quality.
However, I do not have a great perspective on what this looks like under the hood. I got all this information from looking at in-game GUI. Can you maybe test again and compare results?
![](https://u.teknik.io/EyDEq.png)
![](https://u.teknik.io/XunDp.png)

**Comment by Trawis** [comment]
This is wrong approach. ArtProgress & CodeProgress are enough to max out art & code. Problem is team specialization skill. Test it with team/actor who has maximum skills and quality of the product will be high. Maybe I can add fake actor with full specialization skills who will "develop" product in alpha stage. To sum up; If you want have better quality for your product then your team must have better specialization skills, this function just speed up things so you don't need to wait developing time.

**Comment by AdamC1228** [comment]
When I encountered the issue, I had a fully stated team with maximum specialization skills in all categories. When I would max the code and the art they would go to an odd percentage. Like for instance. Lets say that the alpha percentage was at 24% art completion. Upon maxing the art for the specified project it would go to something like 2.58%. Not the 100% completion that is expected.

Again this was on 10.2.1 and the value I suggested the following: "Set the ArtDevTime to be the complementary multiple to produce 100% completion." What those values are or should be are beyond my knowledge of the game's inner workings. Just from fiddling around and attempting to learn how these components interact on a trial an error basis was how I came to the DevTime * ArtProgress = PercentComplete conclusion.

**Comment by Trawis** [comment]
ArtProgress is float and value 1 is representing 100%, 0.98 = 98% etc.
I was testing it and if you have fully qualified team who is assigned for that project then quality should be maxed out, but again, should. If you can reproduce this situation please post it here. Maybe some video.

P.S. Where did you found percentage that is needed for completion? Art/Code units doesn't represent progress in %.
