### ISSUE TITLE
Trainer's Window Disappears Frequently

### ISSUE THREAD

**Issue by Kr4ken-9** [Trawis/SoftwareIncDLLModifications#8]
As reported by [Dingus](https://steamcommunity.com/profiles/76561198008258908) in the steam workshop, the trainer window will disappear (frequently) under certain circumstances:
1. Changing Locations
2. Loading a different save

**Comment by Trawis** [comment]
Known issue, I'm looking for solution.

**Comment by Trawis** [comment]
Workaround: Change location, save then quit to the main menu and load game again.
